### ISSUE TITLE
Implement what happens when comment period is closed

### ISSUE THREAD

**Issue by jehlers** [eregs/notice-and-comment#183]
- [x] Hide sidebar links to "write a comment"
- [x] Changing the preamble introduction (https://github.com/eregs/notice-and-comment/issues/106#issuecomment-212603007) and 
- [x] Update the homepage (https://github.com/eregs/notice-and-comment/issues/183#issuecomment-220681553) to mention the closed comment period
- [x] ~~Taking away the date from the right sidebar and replacing it with "Comment period has ended"~~ (we punted #191)
- [x] Allow the write tab to be clicked on, but replace write mode with a message that explains the comment period is over and sends users to the docket folder with all the comments (https://github.com/eregs/notice-and-comment/issues/236#issuecomment-217993811)

**Comment by jehlers** [comment]
Design for the last checkbox from #236:

> Allow the write tab to be clicked on, but replace write mode with a message that explains the comment period is over and sends users to the docket folder with all the comments

![96375408-160a-11e6-8f8b-972d120342d0](https://cloud.githubusercontent.com/assets/4267825/15163506/ef142822-16d6-11e6-8ffc-87e621a62c66.png)

**Comment by jehlers** [comment]
For the third bullet above, here's a design for what we can do when the comment period closes on the homepage:

- Leave countdown at 0
- Add the red ! icon next to the end date
- Change "Ends" to "Ended" 
- Disable the button / swap out for closed message and link to just reading the proposal

![closed 7](https://cloud.githubusercontent.com/assets/4267825/15437601/02224810-1e96-11e6-9d49-d4a2d54a9d85.png)

**Comment by cmc333333** [comment]
I _think_ @jmcarp's implemented some of this. We'll need to validate

**Comment by cmc333333** [comment]
@tadhg-ohiggins is handling the home page part

**Comment by cmc333333** [comment]
All merged in
