### ISSUE TITLE
Write mode CSS polish

### ISSUE THREAD

**Issue by jehlers** [eregs/notice-and-comment#354]
**HIGHEST PRIORITY**
- [ ] Link underlines and expand text should be link blue (same as the buttons #0072CE not the tabs)
- [ ] Gray background of both the expand excerpt bar and the pending comments should be #f5f5f5
- [ ] Take out “more context for” so the bar just says “Show”
- [ ] Save response and upload attachments buttons should be the same size and on the same line (I would keep the height and spacing of the upload attachment button and match the save response button to that.)

**MEDIUM**
- [ ] Citation in gray excerpt should be dark gray #767676
- [ ] “You’ve uploaded X total attachments….” warning should also be #767676

cc @xtine and @donjo

**Comment by xtine** [comment]
@donjo: right now link colors are set as `@link_blue: #0071BC;`, should it be #0072CE or otherwise?

**Comment by xtine** [comment]
@jehlers:
I just realized that the designs have a "Delete response" link now. Currently that space is taken up when there are multiple attachments, like so:
<img width="628" alt="screen shot 2016-06-07 at 6 22 17 pm" src="https://cloud.githubusercontent.com/assets/24054/15879892/f2fe2156-2cdc-11e6-8f2f-bbf0c8e0122c.png">

Should the attachments have a max width (and truncated with ... if it is a long file name) to leave room for the "Delete response" link, and just stack vertically instead of filling space horizontally as it is now?

**Comment by donjo** [comment]
Yeah those attachments should stack vertically, I must have changed something at some point and forgot to re-check with a short file name.

**Comment by jehlers** [comment]
Yeah, sorry I was also expecting the files to stack vertically.
